---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "API Meuble TV"
host: "192.168.1.139:8080"
basePath: "/api"
tags:
- name: "meuble_tv"
  description: "Exécuter des scénario ou commandes autour du meuble_tv"
schemes:
- "http"
- "https"
paths:
  /meuble_tv/scenario/{scenario}:
    get:
      tags:
      - "meuble_tv"
      operationId: "meuble_tv_scenario"
      produces:
      - "application/json"
      parameters:
      - name: "scenario"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "string"
            example: "S1"
        400:
          description: "Erreur"
      x-swagger-router-controller: "MeubleTv"
  /meuble_tv/color/{color}:
    get:
      tags:
      - "meuble_tv"
      operationId: "meuble_tv_color"
      produces:
      - "application/json"
      parameters:
      - name: "color"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "string"
            example: "C113388"
        400:
          description: "Erreur"
      x-swagger-router-controller: "MeubleTv"
  /meuble_tv/command/{command}:
    get:
      tags:
      - "meuble_tv"
      operationId: "meuble_tv_command"
      produces:
      - "application/json"
      parameters:
      - name: "command"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Erreur"
      x-swagger-router-controller: "MeubleTv"
definitions: {}
